Program no. 3

Implementing deep Neural Network for performing classification task(diabetes detection)

In [15]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense

In [3]:
dataset=loadtxt('pima-indians-diabetes.csv',delimiter=',')
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [7]:
X=dataset[:,0:8]
Y=dataset[:,8]


In [8]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [9]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [10]:
model=Sequential()

In [11]:
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [12]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,Y,epochs=150,batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 10.5174 - accuracy: 0.3490
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 2.4067 - accuracy: 0.4948
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8785 - accuracy: 0.5885
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7135 - accuracy: 0.6406
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6963 - accuracy: 0.6432
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.6458
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6789 - accuracy: 0.6510
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6742 - accuracy: 0.6497
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6695 - accuracy: 0.6510
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6665 - accuracy: 0.6536
Epoch 11

In [13]:
predictions=model.predict(X)

In [14]:
predictions

array([[0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.33291113],
       [0.9770013 ],
       [0.33291113],
       [0.332