                     
Program no. 1   
Performing matrix multiplication and eigen vectors and given value using tensorflow 

In [15]:
import tensorflow as tf
print("Matrix Multiplication Demo")
x=tf.constant([1,2,3,4,5,6],shape=[2,3])
print(x)


Matrix Multiplication Demo
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [16]:
y=tf.constant([7,8,9,10,11,12],shape=[3,2])
print(y)
z=tf.matmul(x,y)
print("Product:",z)


tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Product: tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [9]:
e_matrix_A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32,name="matrix A")
e_matrix_A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6.804909 , 8.108532 ],
       [8.12319  , 4.0950885]], dtype=float32)>

In [17]:
eigen_values_A,eigen_vectors_A=tf.linalg.eigh(e_matrix_A)

print(eigen_vectors_A)

tf.Tensor(
[[-0.64632714  0.76306045]
 [ 0.76306045  0.64632714]], shape=(2, 2), dtype=float32)


In [11]:
print(eigen_values_A)

tf.Tensor([-2.7854123 13.6854105], shape=(2,), dtype=float32)
